# Generated by Django 4.2.16 on 2024-09-24 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Current location'), (1, 'Past adventure')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_stamps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='blog.stamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
