# Generated by Django 4.2.16 on 2024-09-23 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='newpost',
            name='country',
            field=django_countries.fields.CountryField(default='United Kingdom', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newpost',
            name='status',
            field=models.IntegerField(choices=[(0, 'Current location'), (1, 'Past adventure')], default=0),
        ),
        migrations.AddField(
            model_name='newpost',
            name='user',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(upload_to='media/blog_images/'),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
