# Generated by Django 4.2.16 on 2024-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
