# Generated by Django 4.2.16 on 2024-09-30 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rating_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.stamp'),
        ),
    ]
