# Generated by Django 4.2.16 on 2024-10-02 10:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_rating_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamp',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
