# Generated by Django 4.2.16 on 2024-10-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_stamp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
